### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by yoavst** [nsk-mironov/kotlin-jetpack#1]
Why do you add `bind` before any delegation? there is not Kotlin stdlib delegation that start with bind.
`val booleanOrThrow: Boolean by booleanArgument("extra_boolean")`

also for resources, I think it is more readable:

``` kotlin
val text by stringResource(R.string.text)
val number by intResource(R.integer.number)
val dimenPixelSize by dimenResource(R.dimen.size)
val color by colorResource(R.color.red)
val intArray by intArrayResource(R.array.ids)
val stringArray by stringArrayResource(R.array.options)
val drawable by drawableResource(R.drawable.background)
```

**Comment by nsk-mironov** [comment]
I'm using [kotterknife](https://github.com/JakeWharton/kotterknife) a lot and it has the same naming convention. I just wanted to be consistent.

**Comment by dsvoronin** [comment]
+1 @yoavst, its better without bind
@nsk-mironov maybe you just add kotterknife to your project, shorten namings and maintain it?
Seems Jake don't have time for it, (better ask him first ofc)

**Comment by nsk-mironov** [comment]
@yoavst @dsvoronin ok, I can go totally crazy and just use generics everywhere. In this case all `bindXXX` methods will be replaced with three simple methods:

``` kotlin
var firstName by argument<String>()
var lastName by argument<String>()
var age by argument<Int>()

var background by resource<BitmapDrawable>(R.drawable.background)
var foreground by resource<VectorDrawable>(R.drawable.foreground)

val color by resource<Int>(R.color.primary)
val size by resource<Int>(R.dimen.size)

var endpoint by preference<String>(default = "https://api.github.com")
var enabled by preference<Boolean>(default = true)
```

What do you think?

**Comment by dsvoronin** [comment]
@nsk-mironov :+1:

**Comment by yoavst** [comment]
It will have performance impact.

**Comment by dsvoronin** [comment]
@yoavst it is doubtful. if it will be like +1% of component startup time, because reflection call (which is super fast on android if not about annotations reading afaik) - that's worth it

**Comment by yoavst** [comment]
So, is there any update?

**Comment by nsk-mironov** [comment]
I'll replace all `bindXXX` methods with simple generics, because it's required for some features I'm going to introduce in future releases. I still haven't decided which naming convention to choose, but I think I'll leave everything as it is:

``` kotlin
var firstName by bindArgument<String>()
var lastName by bindArgument<String>()
var age by bindOptionalArgument<Int?>()

var background by bindResource<BitmapDrawable>(R.drawable.background)
var foreground by bindResource<VectorDrawable>(R.drawable.foreground)

val color by bindResource<Int>(R.color.primary)
val size by bindResource<Int>(R.dimen.size)

var endpoint by bindPreference<String>(default = "https://api.github.com")
var token by bindOptionalPreference<String?>()
```

**Comment by yoavst** [comment]
Maybe you can provide module with bind and module without bind, if you so like the bind keyword.

**Comment by nsk-mironov** [comment]
No, having two artifacts with the same functionality but different names isn't a solution. Anyone who doesn't like these names so much can always create a simple wrapper around the library.
