### ISSUE TITLE
Should arguments be cached?

### ISSUE THREAD

**Issue by nsk-mironov** [nsk-mironov/kotlin-jetpack#14]

**Comment by cypressious** [comment]
The intent of an Activity can be changed when it's running. If you cache the extras, they can become wrong when the intent is changed.

**Comment by nsk-mironov** [comment]
Good point. I had a feeling that it's not a good idea to cache them, but I couldn't find a use case when it's really bad. Thank you for sharing this use case, I'll remove caching in next release.

**Comment by cypressious** [comment]
if you drop caching, you could implement the delegates as extension functions on the extras, something like `fun<T> Bundle.get(...) : ReadWriteProperty`. This would reduce the number of classes, which is always nice.

**Comment by nsk-mironov** [comment]
And how would you use these functions? Something like the code below won't work, since there is no `arguments` at the moment when delegates are created:

``` kotlin
public class UserFragment : Fragment() {
    public var firstname: String by arguments
    public var lastname: String by arguments
}
```

**Comment by nsk-mironov** [comment]
And there is no way to provide a default value or custom extra name (or at least I'm not aware how to do it).

**Comment by cypressious** [comment]
You could have a helper function that lazily returns the arguments, however this would introduce some new classes again. Might still be fewer classes than in the current approach, but I'd have to test.

Btw, did you test if your example doesn't work? I haven't looked at the generated code for a delegate, yet, so I don't know if the instance needs to be available at declaration time.

**Comment by cypressious** [comment]
Default values are a problem, I agree.

**Comment by nsk-mironov** [comment]
> Btw, did you test if your example doesn't work? I haven't looked at the generated code for a delegate, yet, so I don't know if the instance needs to be available at declaration time.

Yes, delegates are created at the declaration time, so all the values have to be available at that moment.
